### ISSUE TITLE
If you want, we can merge this translation with the original book

### ISSUE THREAD

**Issue by thewhitetulip** [kevingo/web-dev-golang-anti-textbook-zh-tw#2]
Please send a PR if you want to add this to the English translation

**Comment by kevingo** [comment]
@thewhitetulip Thanks. I will send a PR after I finishing the translation task.

**Comment by thewhitetulip** [comment]
The thing is, I have made massive changes to the book in the meanwhile, I would request you to take the latest source and then translate it, so that your efforts don't go waste.

**Comment by kevingo** [comment]
@thewhitetulip thanks for remind. I will keep the latest content.
