### ISSUE TITLE
License infringement

### ISSUE THREAD

**Issue by thewhitetulip** [kevingo/web-dev-golang-anti-textbook-zh-tw#3]
This project is infringing the license, please provide proper attribution in the readme:

https://github.com/thewhitetulip/web-dev-golang-anti-textbook#license

**Comment by kevingo** [comment]
@thewhitetulip sorry for the license issue, I open an [issue](https://github.com/kevingo/web-dev-golang-anti-textbook-zh-tw/issues/4) for solving it.

**Comment by kevingo** [comment]
@thewhitetulip Fix the content issue, please check ~
